### ISSUE TITLE
Einfachere Sprache

### ISSUE THREAD

**Issue by JulianRoesner** [covid-zu-hause/covid-zu-hause.github.io#2]
Hi, 

we've noticed, that the German version uses lots of long sentences and is sometimes quite hard to understand. A friend and I would try to translate it into a more simple language, and issue a pull request afterwards. Would that be cool?

**Comment by ropg** [comment]
Ja natürlich, ganz gerne...

**Comment by ropg** [comment]
Julian? Koenntest du uns mal direkt kontaktieren? Weil es waere wirklich cool wenn das bald passieren koennte, und wir haben u.U. noch paar mehr freiwillige. Vielleicht kommste mal im [team chat](https://meet.jit.si/OngoingTeamMeetingForCovidAtHome) vorbei?

**Comment by JulianRoesner** [comment]
Pull Request wurde gerade gesendet. Team chat funktioniert bei mir leider nicht
